---
settings:
  name: ONTAP Cloud 9.3 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: ONTAP クラウド
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  - name: Cloud Volumes ONTAP 最新
    url: "/cloud-volumes-ontap-relnotes"
    version-number: ''
  - name: その他のバージョン
    url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-other-versions.html
    version-number: ''
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: リリースノートのホーム
    url: "/index.html"
  - title: 新機能
    url: "/reference-new.html"
  - title: サポートされている構成
    url: "/reference-supported-configs.html"
  - title: ストレージの制限
    url: "/reference-storage-limits.html"
  - title: 既知の問題
    url: "/reference-issues.html"
  - title: 既知の制限
    url: "/reference-limitations.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 新機能
      url: reference-new.html
  - title: 構成と制限
    links:
    - title: サポートされている構成
      url: reference-supported-configs.html
    - title: ストレージの制限
      url: reference-storage-limits.html
    - title: 制限
      url: reference-limitations.html
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Cloud Manager のすべてのドキュメント
